### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by jkcv** [ManyDesigns/Portofino#275]
I am launching a brand new Portofino setup. I am receiving "Server error" on the page to select schema. Here are the steps to reproduce the error.

1) Brand new setup
2) Login
3) Click Administration
4) Click wizard
5) Leave selection JDBC as is
6) Enter database name
7) Select driver as PostgreSQL
8) Enter local (private) IP for database server, which is another machine on local network
9) Add valid user and password
10) Click "Next"
11) This should list the schemas of the database, but does not and at the bottom center a black window appears that says, "Server error                    OK" (the OK is in pink)

12) Repeat steps 2 - 7, enter localhost for step 8, repeat steps 9 - 11 - get the same error message.

13) Steps 1 - 11, except enter 127.0.0.1 instead of "localhost" in step 8 - get the same error message.

14) Steps 1 - 11, except enter local IP for localhost
 instead of "localhost" in step 8 - get the same error message.

At first, I thought it was a firewall issue, but that can't be in steps 12 - 14.

What am I doing wrong?

Thanks

Joe

![errormsg](https://user-images.githubusercontent.com/44293329/67541612-8f970d00-f6b7-11e9-9b4b-a697102a1fd5.png)

**Comment by alessiostalla** [comment]
Can you attach your Tomcat logs or send them to the mailing list / Google group?

Thanks.

**Comment by jkcv** [comment]
Thanks Allessio

Below are the last 100 lines of the catalina.out log. In the very beginning it says, "No suitable driver found." This is quite confusing since the connections button reports that the driver is OK:

CONNECTION BUTTON report:
Description | Standard driver class name | Status
-- | -- | --
MariaDB | org.mariadb.jdbc.Driver | driver not found
Microsoft SQL Server | com.microsoft.sqlserver.jdbc.SQLServerDriver | driver not found
**_PostgreSQL | org.postgresql.Driver | ok_**
MySQL 5.x | com.mysql.jdbc.Driver | ok
IBM DB2 | com.ibm.db2.jcc.DB2Driver | driver not found
H2 | org.h2.Driver | driver not found
Apache Derby | org.apache.derby.jdbc.EmbeddedDriver | driver not found
Microsoft SQL Server (jTDS driver) | net.sourceforge.jtds.jdbc.Driver | ok
Google Cloud SQL | com.google.appengine.api.rdbms.AppEngineDriver | driver not found
IBM DB2 for iSeries (AS/400) | com.ibm.as400.access.AS400JDBCDriver | driver not found
IBM DB2 for ZOS | com.ibm.db2.jcc.DB2Driver | driver not found
Oracle | oracle.jdbc.driver.OracleDriver | driver not found

Since I am using PostgreSQL, how can the log report not finding driver, while connections reports finding it?

Another error, which may or may not be related to this is a server error when I try to change the password.

Thanks again for your help

Joe

==========================
CATALINA.OUT (last 100 lines)
==========================
2019-10-28 16:26:16,884 INFO  com.manydesigns.portofino.access         admin /api/portofino-upstairs/database/connections GET
2019-10-28 16:26:16,909 INFO  com.manydesigns.portofino.access         admin /api/:description GET
2019-10-28 16:27:01,595 INFO  com.manydesigns.portofino.access         admin /api/portofino-upstairs/database/connections POST
2019-10-28 16:27:01,598 INFO  c.m.portofino.persistence.Persistence    admin /api/portofino-upstairs/database/connections Cleaning up old setups
2019-10-28 16:27:01,598 WARN  c.m.p.m.database.JdbcConnectionProvider  admin /api/portofino-upstairs/database/connections Could not create database platform for proposal
java.sql.SQLException: No suitable driver found for 10.66.78.111:5432
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.manydesigns.portofino.model.database.JdbcConnectionProvider.acquireConnection(JdbcConnectionProvider.java:122)
	at com.manydesigns.portofino.model.database.ConnectionProvider.init(ConnectionProvider.java:115)
	at com.manydesigns.portofino.model.database.JdbcConnectionProvider.init(JdbcConnectionProvider.java:108)
	at com.manydesigns.portofino.persistence.Persistence.initModel(Persistence.java:276)
	at com.manydesigns.portofino.upstairs.actions.database.connections.ConnectionsAction.doCreateConnectionProvider(ConnectionsAction.java:127)
	at com.manydesigns.portofino.upstairs.actions.database.connections.ConnectionsAction.saveConnectionProvider(ConnectionsAction.java:169)
	at com.manydesigns.portofino.upstairs.actions.database.connections.ConnectionsAction.createConnection(ConnectionsAction.java:118)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.manydesigns.portofino.servlets.CleanupFilter.doFilter(CleanupFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.manydesigns.portofino.servlets.I18nFilter.doFilter(I18nFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.manydesigns.portofino.servlets.LocaleAndEncodingFilter.doFilter(LocaleAndEncodingFilter.java:43)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.manydesigns.elements.servlet.ElementsFilter.doHttpFilter(ElementsFilter.java:147)
	at com.manydesigns.elements.servlet.ElementsFilter.doFilter(ElementsFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:352)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:171)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-10-28 16:27:01,600 INFO  c.m.portofino.persistence.Persistence    admin /api/portofino-upstairs/database/connections Cleaning up old setups

**Comment by alessiostalla** [comment]
"10.66.78.111:5432" is not a valid JDBC url, you'll want something like
this: jdbc:postgresql:10.66.78.111:5432/databaseName (check the PostgreSQL
JDBC documentation)

**Comment by jkcv** [comment]
Hi Alessio

That took care of it.

In case anyone is having a similar issue, the exact connection URL that worked was:

jdbc:postgresql://localhost/proposal

Note that "proposal" is my database and you would substitute for your case.

Thanks again!

Joe
